// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';


function b(c, d) {
  return c + d | 0;
}

console.log(3);

console.log("Hello, BuckleScript and Reason!");

console.log("Hi stu");

console.log("The answer is no");

var a = "sdad";

exports.a = a;
exports.b = b;
/*  Not a pure module */
